### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by grzmyr** [ltrr-arizona-edu/tellervo#110]
Reading or writing from/to database shows:

> ERROR:  function cpgdb.getvmeasurementresult(unknown) does not exist
> LINE 1: SELECT * FROM cpgdb.getvmeasurementresult('683c7268-14dc-11e...                      ^
> HINT:  No function matches the given name and argument types. You might need to add
> explicit type casts.
> Error code: SQL_ERROR

Latest: Tellervo Server v 1.3.2  and Desktop 1.3.4

**Comment by petebrew** [comment]
Solved in v1.3.3 of Tellervo Server
