### ISSUE TITLE
I/O Error when saving a new Series

### ISSUE THREAD

**Issue by WillametteDendro18** [ltrr-arizona-edu/tellervo#111]
I am trying to save a new Series but an I/O Error won't let me save. 
" There was an error while saving the file: 
Unknown tag &lt;tridas:lastYear&gt;. Tag is being ignored
Error code: INVALID_USER_PARAMETERS "

![i_oerror](https://user-images.githubusercontent.com/36682644/36456123-3ecf7bf0-1658-11e8-809d-51ffaf18cc03.PNG)

**Comment by petebrew** [comment]
This looks as though the server was not configured correctly.  There was an error in the VirtualBox deployed version 1.3.2, that was fixed as part of v1.3.3.  If you're still having trouble, please download the latest version of the server and try again.

**Comment by WillametteDendro18** [comment]
Is there a suggested Windows version that works best? We are using Windows 7 at the moment. We downloaded already but will try again.

**Comment by petebrew** [comment]
The VirtualBox server will run on any operating system.  Version 1.3.3 was released on 2nd March 2018 so given the age of this ticket, I'm guessing you must be using the previous v1.3.2 (which includes a bug which would explain the screenshot you posted).  Or perhaps you missed the requirement for Tellervo Server entirely?  If it's the latter, take a look at the Tellervo manual (http://tellervo.org/support/) which describes the steps to deploy a Tellervo Server.
