### ISSUE TITLE
Reverse series menu option-no indicator or warning

### ISSUE THREAD

**Issue by gcaha** [ltrr-arizona-edu/tellervo#118]
The Reverse series Tools menu option is right next to Redate, with no warning like "Are you sure you want to reverse?" Then there is no indicator that a series has been reversed.  What this means in practice, is that an accidental menu selection can be very confusing if you don't know it was selected.  The data is still there, but you won't know if its been reversed or not without some time sucking investigation.

**Comment by petebrew** [comment]
Confirmation dialog added in DEV and available in latest snapshot release
