### ISSUE TITLE
Install from .deb for client version >= 1.2.0 does not create .desktop application file

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#32]
Installing Tellervo desktop client onto a Linux *buntu system (version 14.04 LTS) with .debs does not create a .desktop application file. This only seems to apply to Tellervo clients 1.2.0 and up.

Normally, we would find a .desktop file for the Tellervo client in /usr/share/applications . This file allows desktop software (such as Unity) to directly launch Tellervo. Without this .desktop file, users need to launch Tellervo from the command line. This could be a problem for less tech-savvy users.

**Comment by petebrew** [comment]
Seems to be an oversight in the switch from jdeb to install4j for building the installers.
