### ISSUE TITLE
Importing GPX files with bulk import dialog does not include "altitude" measurements.

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#35]
As an aside, "altitude" should be "elevation" in the tridas standard. "Altitude" suggests that our trees are flying above the ground. :-\

...Anyways, it would be great if we could get elevation measurements from GPX files along with latitude and longitude.

**Comment by petebrew** [comment]
Yes this was a translation issue and is already on the 'fix list' for 
the next version of TRiDaS.  I blame myself for letting it slip through.
