### ISSUE TITLE
Exception thrown when adding location to tridas.object in meta data browser

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#36]
Tridas v1.2.0 on Ubuntu 14.04

To reproduce:

* Launch desktop client. Login to Tellervo server. Open metadata browser. 

* Select tridas.object (site) without location information in left-side treeview. Select padlock in right panel to unlock editing.

* Open "Location" element in right panel. Select to edit "Location geometry". Manually insert location in pop-up box (lat: 37.933; lon: -109.8). Select "okay".

* In metadata browser select "Save changes".

* Boom goes the dynamite. (Get popup on internal error while accessing resources.)

[tellervo-submission.log](https://github.com/ltrr-arizona-edu/tellervo/files/14207/tellervo-submission.txt) is attached.

**Comment by brews** [comment]
This might be a part of a more serious problem, or a separate bug:

I've gone back and looked at Elements that I've entered lat lon from GPX on bulk entry. These are entries where the values seemed to have been accepted. If I go back and find these Elements in the metadata browser, Location's lat and lon appear to be empty.

On this same Element, I can attempt to correct the missing lat lons by putting lat lon values into the field through the meta data browser (connecting it with GPX file waypoints). They appear to read correctly in the GUI and I can confirm this in the outgoing Element's XML. But reloading the Element in the browser after this exchange sill shows no lat lon.

**Comment by brews** [comment]
On sites that had location added in previous versions of Tellervo, the location still shows in Meta Data browser. I'm just not seeing lat lon from new bulk entry, through.

**Comment by brews** [comment]
Tried this by creating an actual sample and then editing through the "metadata" tab. After editing location, XML for [1] element gives message code 998:

"PHP Notice - Trying to get property of non-object."

**Comment by petebrew** [comment]
Problem caused by a change in namespace handling for GML tags.
