### ISSUE TITLE
Cannot edit Element samplingDate in bulk data entry or meta data browser

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#37]
Tellervo v1.2.0. Ubuntu 14.04

It would be nice to be able to enter tridas Element samplingDate in the bulk data entry dialog, in the meta data browser, or the "meta" tab of the main window when a sample is active
.

This is a *very important* field to have easily visible and editable for climate/hydro people.

In bulk data entry, there is a field for this and I can highlight the cell but I cannot enter values.

**Comment by petebrew** [comment]
Date editor is already working in Metadata Browser, and on metadata tab of main editor but you need to use the calendar popup dialog, you cannot type the date in.  Working on implementing the editor in the bulk data entry table.
