### ISSUE TITLE
Species pull-down list for Taxon fields is not consistently alphabetized.

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#38]
Tellervo v1.2.0

I believe that the species pull-down for Taxon is intended to be alphabetized (correct me if I'm wrong). There are occasional breaks in the ordering where items appear out of order.

This makes it very difficult to select spp from the large pull-down.

**Comment by petebrew** [comment]
I've not been able to replicate this

**Comment by brews** [comment]
It's fixed in latest release. Closing.
