### ISSUE TITLE
'Duplicate key value violates unique constraint "pkey_object"' error in meta data browser edit

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#43]
Tellervo 1.2.0

Open Tellervo meta data browser and double-click tridas object that was recently created.
Edit text field like "Creator" or "Comment" fields and then click button to "Save changes" results in this error.

Not exclusive to text fields (get same error when trying to edit "postal code").

Unable to edit meta data. :-(

**Comment by petebrew** [comment]
Unable to replicate this.  Is it still a problem?

**Comment by brews** [comment]
Yup. I'm still getting it on the 1.2.1-SNAPSHOT.

I can swing by your office next week and we can pick through this if you'd like.
