### ISSUE TITLE
Lockup when clicking "Provide GPS data file" button with "Elements" tab in bulk entry window.

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#45]
v1.2.1-SNAPSHOT

Open Tellervo desktop client. Go to bulk data entry from File dropdown menu. Click "Elements" tab at bottom of the bulk entry window. Click the "Provide GPS data file" toolbar button. Empty dialog window opens and program locks up. Have to `killall java` to put program Tellervo in the grave.

**Comment by petebrew** [comment]
Can't replicate on my machine.  Can you send me the GPS file you tried - perhaps there is a problem with it or my code for parsing.

**Comment by brews** [comment]
Yeah, I can replicate this in the latest dev release. I'll close this.
