### ISSUE TITLE
Unable to add new users without error

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#55]
v1.2.1-March 3

This also is a problem in the snapshot.

Open 'Create user' dialog from desktop client.

Entering new user with all unique fields:

Enter first/last name, user name, double click checkbox to give admin rights (single click doesn't work on checkboxes, FYI), enter password, confirm password.

Click 'create' button on bottom of dialog and get error pop-up: "Error creating user. Make sure the username is unique.The request sent to the server was invalid.  This typically means mandatory fields were missing".

(ノಠ益ಠ)ノ彡┻━┻

**Comment by petebrew** [comment]
Typo in SQL insert statement.
