### ISSUE TITLE
ctrl-delete keyboard shortcut not responsive

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#57]
v2.1 build from 10:44 01-Mar-2016 on Ubuntu Linux 14.04 LTS

On the "data" tab for a series, if I select a year on that series and hit ctrl+delete, nothing happens. Right-click on the same selection and then choosing "Delete year" from that context menu works just fine.

ctrl+delete is what the context menu advertises as the keyboard shortcut to "Delete year" but the shortcut does not seem to work.

**Comment by petebrew** [comment]
Conflict between key listeners.  Other shortcuts also broken.
