### ISSUE TITLE
Database Species Requests

### ISSUE THREAD

**Issue by crollinson** [ltrr-arizona-edu/tellervo#96]
Unless there's an option to add species ourselves that we missed, several of our species are not in the current database.  At the moment, they include:

1. _Prunus serotina_ (black cherry)
2. _Ostrya virginiana_ (ironwood aka hop hornbeam)
3. _Quercus macrocarpa_ (Bur oak)

**Comment by petebrew** [comment]
We're awaiting a long update of the taxonomic dictionary. In the mean time I've added these three manually.
